# Generated by Django 5.0.4 on 2024-11-01 11:56

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BossModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Минакову Вадиму Александровичу', max_length=128, null=True, verbose_name='Имя руководителя')),
            ],
        ),
        migrations.CreateModel(
            name='HrEmailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128, verbose_name='Почта отдела кадров')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_name', models.CharField(max_length=128, verbose_name='Название вакансии')),
                ('salary', models.CharField(max_length=256, verbose_name='Оклад')),
                ('short_description', models.TextField(blank=True, max_length=128, verbose_name='Краткое описание')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание вакансии')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VacancyRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='ФИО')),
                ('contact', models.CharField(max_length=512, verbose_name='Контактная информация')),
                ('covering_letter', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Сопроводительное письмо')),
                ('resume_upload', models.FileField(blank=True, null=True, upload_to='resume_files/', verbose_name='Файл с резюме')),
                ('vacancy', models.CharField(blank=True, max_length=128, verbose_name='Название вакансии, опционально')),
            ],
        ),
        migrations.CreateModel(
            name='VacationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('vacation_date_start', models.DateField(max_length=128)),
                ('vacation_date_end', models.DateField(max_length=128)),
                ('vacation_file', models.FileField(blank=True, null=True, upload_to='vacation_file_scan/%Y/%m/%d')),
                ('status_confirm', models.CharField(choices=[('На согласовании', 'На согласовании'), ('Согласовано', 'Согласовано'), ('Отказ', 'Отказ')], default=('На согласовании', 'На согласовании'), max_length=128)),
                ('vacation_type', models.CharField(choices=[('Оплачиваемый отпуск', 'Оплачиваемый отпуск'), ('За счет сотрудника', 'За счет сотрудника')], default=('Оплачиваемый отпуск', 'Оплачиваемый отпуск'), max_length=128)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_app.jobmodel')),
            ],
        ),
    ]
