# Generated by Django 5.0.4 on 2024-11-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Заголовок')),
                ('feedback_type', models.CharField(blank=True, choices=[('general', 'Общие отзывы'), ('management', 'Отзывы о руководстве'), ('colleague', 'Отзывы о коллегах'), ('project', 'Отзывы о проектах'), ('workplace', 'Отзывы о рабочем месте'), ('policy', 'Отзывы о политике компании'), ('process', 'Отзывы о процессах'), ('events', 'Отзывы о корпоративных мероприятиях'), ('training', 'Отзывы о тренировках и обучении'), ('communication', 'Отзывы о коммуникации'), ('ideas', 'Идеи и инновации')], max_length=256, null=True, verbose_name='Тип отзыва')),
                ('content', models.TextField(max_length=2048, verbose_name='Анонимный отзыв')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
