# Generated by Django 5.0.4 on 2024-06-22 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BossModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Минакову Вадиму Александровичу', max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HrEmailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='VacationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('vacation_date_start', models.DateField(max_length=128)),
                ('vacation_date_end', models.DateField(max_length=128)),
                ('vacation_file', models.FileField(blank=True, null=True, upload_to='vacation_file_scan/%Y/%m/%d')),
                ('status_confirm', models.CharField(choices=[('На согласовании', 'На согласовании'), ('Согласовано', 'Согласовано'), ('Отказ', 'Отказ')], default=('На согласовании', 'На согласовании'), max_length=128)),
                ('vacation_type', models.CharField(choices=[('Оплачиваемый отпуск', 'Оплачиваемый отпуск'), ('За счет сотрудника', 'За счет сотрудника')], default=('Оплачиваемый отпуск', 'Оплачиваемый отпуск'), max_length=128)),
                ('boss_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_app.bossmodel')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_app.jobmodel')),
            ],
        ),
    ]
