# Generated by Django 5.0.4 on 2024-06-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0002_vacancymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancymodel',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
