# Generated by Django 5.0.4 on 2024-06-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0003_vacancymodel_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancymodel',
            name='short_description',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
