# Generated by Django 5.0.4 on 2024-06-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0004_vacancymodel_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancymodel',
            name='short_description',
            field=models.TextField(blank=True, max_length=128),
        ),
    ]
