# Generated by Django 5.0.4 on 2024-06-25 13:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0006_rename_short_description_vacancymodel_краткое_описание'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancymodel',
            name='Краткое описание',
        ),
        migrations.AddField(
            model_name='vacancymodel',
            name='short_description',
            field=models.TextField(blank=True, max_length=128, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='bossmodel',
            name='name',
            field=models.CharField(default='Минакову Вадиму Александровичу', max_length=128, null=True, verbose_name='Имя руководителя'),
        ),
        migrations.AlterField(
            model_name='hremailmodel',
            name='email',
            field=models.EmailField(max_length=128, verbose_name='Почта отдела кадров'),
        ),
        migrations.AlterField(
            model_name='vacancymodel',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание вакансии'),
        ),
        migrations.AlterField(
            model_name='vacancymodel',
            name='salary',
            field=models.CharField(max_length=256, verbose_name='Оклад'),
        ),
        migrations.AlterField(
            model_name='vacancymodel',
            name='vacancy_name',
            field=models.CharField(max_length=128, verbose_name='Название вакансии'),
        ),
    ]
