# Generated by Django 5.0.4 on 2024-06-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0007_remove_vacancymodel_краткое_описание_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('contact', models.TextField(max_length=512)),
                ('resume_upload', models.FileField(blank=True, null=True, upload_to='resume_file/%Y/%m/%d')),
            ],
        ),
    ]
