# Generated by Django 5.0.4 on 2024-06-26 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0008_vacancyrequestmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancyrequestmodel',
            old_name='name',
            new_name='vacancy_name',
        ),
    ]
