# Generated by Django 5.0.4 on 2024-06-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0009_rename_name_vacancyrequestmodel_vacancy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyrequestmodel',
            name='vacancy',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
