# Generated by Django 5.0.4 on 2024-06-26 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0010_vacancyrequestmodel_vacancy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancyrequestmodel',
            old_name='vacancy_name',
            new_name='name',
        ),
    ]
