# Generated by Django 5.0.4 on 2024-06-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0011_rename_vacancy_name_vacancyrequestmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyrequestmodel',
            name='resume_upload',
            field=models.FileField(blank=True, null=True, upload_to='resume_files/'),
        ),
    ]
