# Generated by Django 5.0.4 on 2024-06-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0012_alter_vacancyrequestmodel_resume_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyrequestmodel',
            name='covering_letter',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Сопроводительное письмо'),
        ),
        migrations.AlterField(
            model_name='vacancyrequestmodel',
            name='contact',
            field=models.CharField(max_length=512, verbose_name='Контактная информация'),
        ),
        migrations.AlterField(
            model_name='vacancyrequestmodel',
            name='name',
            field=models.CharField(max_length=128, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='vacancyrequestmodel',
            name='resume_upload',
            field=models.FileField(blank=True, null=True, upload_to='resume_files/', verbose_name='Файл с резюме'),
        ),
        migrations.AlterField(
            model_name='vacancyrequestmodel',
            name='vacancy',
            field=models.CharField(blank=True, max_length=128, verbose_name='Название вакансии, опционально'),
        ),
    ]
