# Generated by Django 5.0.4 on 2024-07-07 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0013_vacancyrequestmodel_covering_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationmodel',
            name='boss_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_app.bossmodel'),
        ),
    ]
