# Generated by Django 5.0.4 on 2024-11-01 11:56

import apps.about_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutEmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('content', models.CharField(max_length=256, verbose_name='Контент')),
                ('photo', models.ImageField(upload_to=apps.about_app.models.upload_to, verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=128, verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_place', models.CharField(blank=True, max_length=128, null=True, verbose_name='Рабочее место')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceBookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('additional_number', models.IntegerField(blank=True, null=True, verbose_name='Внутренний номер')),
                ('additional_info', models.TextField(blank=True, max_length=512, null=True, verbose_name='Дополнительная информация')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_app.jobmodel')),
                ('work_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='about_app.workplace', verbose_name='Рабочее место')),
            ],
        ),
    ]
