# Generated by Django 5.0.4 on 2024-07-07 10:14

import about_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutemployeemodel',
            name='content',
            field=models.CharField(max_length=256, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='aboutemployeemodel',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='aboutemployeemodel',
            name='photo',
            field=models.ImageField(upload_to=about_app.models.upload_to, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='job_title',
            field=models.CharField(max_length=128, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='referencebookmodel',
            name='additional_info',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='referencebookmodel',
            name='additional_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Внутренний номер'),
        ),
        migrations.AlterField(
            model_name='referencebookmodel',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='referencebookmodel',
            name='work_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='about_app.workplace', verbose_name='Рабочее место'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='work_place',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Рабочее место'),
        ),
    ]
