# Generated by Django 5.0.4 on 2024-07-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('content', models.TextField(max_length=2048, verbose_name='Анонимный отзыв')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
