# Generated by Django 5.0.4 on 2024-07-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0002_feedbackmodel_feedback_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='feedback_type',
            field=models.CharField(blank=True, choices=[('general', 'Общие отзывы'), ('management', 'Отзывы о руководстве'), ('colleague', 'Отзывы о коллегах'), ('project', 'Отзывы о проектах'), ('workplace', 'Отзывы о рабочем месте'), ('policy', 'Отзывы о политике компании'), ('process', 'Отзывы о процессах'), ('events', 'Отзывы о корпоративных мероприятиях'), ('training', 'Отзывы о тренировках и обучении'), ('communication', 'Отзывы о коммуникации'), ('ideas', 'Идеи и инновации')], max_length=256, null=True, verbose_name='Тип отзыва'),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Заголовок'),
        ),
    ]
